Documemtation for security mitigation
janus-idp/operator pull request #182
Opened 2024-01-31 16:09 UTC by jianrongzhang89

## Description
Update the docs related to the security mitigation.

## Which issue(s) does this PR fix or relate to

- Fixes #160 

## PR acceptance criteria

- [ ] Tests
- [ X] Documentation

## How to test changes / Special notes to the reviewer
None

2024-02-01 14:17 UTC, rm3l requested changes

2024-02-01 14:17 UTC, rm3l commented on docs/admin.md
> +It is recommended to deploy the Backstage Operator in a dedicated default namespace `backstage-system`. This allows cluster administrators to restrict that the operator gets installed on particular n
```suggestion
It is recommended to deploy the Backstage Operator in a dedicated default namespace `backstage-system`. This allows cluster administrators to restrict that the operator gets installed on particular namespaces. For instance, the cluster administrator can require that the operator only gets installed on `backstage-system` by creating the following [`OperatorGroup`](https://olm.operatorframework.io/docs/concepts/crds/operatorgroup/):
```

2024-02-01 14:17 UTC, rm3l commented on docs/admin.md
> +You can use the Backstage Operator to deploy a backstage application with your custom backstage image by setting the field `spec.application.image` in your Backstage CR. This is at your own risk and
```suggestion
You can use the Backstage Operator to deploy a backstage application with your custom backstage image by setting the field `spec.application.image` in your Backstage CR. This is at your own risk and it is your responsibility to ensure that the image is from trusted sources, and has been tested and validated for security compliance.
```

2024-02-01 14:19 UTC, rm3l commented on docs/admin.md
> +You can choose to deploy the operator in the `openshift-operators` namespace instead. However, you should keep in mind that the Backstage Operator shares the namespace with other operators and theref
```suggestion
On OpenShift, you can choose to deploy the operator in the `openshift-operators` namespace instead. However, you should keep in mind that the Backstage Operator shares the namespace with other operators, and therefore any users who can create workloads in that namespace can get their privileges escalated from all operators' service accounts.
```

2024-02-01 15:11 UTC, nickboldt requested changes
see comment about default namespace

2024-02-07 01:30 UTC, jianrongzhang89 commented
> We have a problem with the current recommended namespace for RHDH operator install:
> 
> [1f8875b#diff-b62e6ae7fdd151e3ffaea0cfd39b32492fba5ada80a04f64d7646282ac8e39f2R28](https://github.com/janus-idp/operator/commit/1f8875b1b83e20ed708eea26b1b5647975dd1ae0#diff-b62e6ae7fdd151e3ffaea0cfd39b32492fba5ada80a04f64d7646282ac8e39f2R28)
> 
> `forbidden: cannot request a project starting with "openshift-"`
> 
> So while in these docs you use `backstage-system` we would either need to use `rhdh-system` or revert to the default `openshift-operators` namespace.
> 
> Though TBH I'm baffled why we want "system" instead of "operator" since that's the only thing in that namespace, right? all the other pods (openshift4/ose-kube-rbac-proxy, rhdh, postgres) would be in `mybackstage` or `myrhdhinstancefoo` namespace

There are two different conventions for naming namespaces for operators. In k8s, ***-system are widely used, while in OpenShift, ***-operator are commonly  used. So for downstream, I think rhdh-operator is a good name, while for upstream/mid-stream,  backstage-system is a good choice too.

2024-02-07 14:24 UTC, rm3l commented on docs/admin.md
> +On You can use the Backstage Operator to deploy a backstage application with your custom backstage image by setting the field `spec.application.image` in your Backstage CR. This is at your own risk a
```suggestion
You can use the Backstage Operator to deploy a backstage application with your custom backstage image by setting the field `spec.application.image` in your Backstage CR. This is at your own risk and it is your responsibility to ensure that the image is from trusted sources, and has been tested and validated for security compliance.
```

2024-02-07 14:30 UTC, rm3l approved these changes
/hold

@nickboldt Suggested namespace is now `rhdh-operator`, which works with our [install script](https://github.com/janus-idp/operator/blob/main/.rhdh/scripts/install-rhdh-catalog-source.sh). Is that okay for you to merge this PR?

2024-02-08 09:48 UTC, rm3l commented
> /hold
> 
> @nickboldt Suggested namespace is now `rhdh-operator`, which works with our [install script](https://github.com/janus-idp/operator/blob/main/.rhdh/scripts/install-rhdh-catalog-source.sh?rgh-link-date=2024-02-07T14%3A30%3A19Z). Is that okay for you to merge this PR?

/hold cancel

Merging this to unblock the doc part.

2024-02-08 09:52 UTC, merged