[WIP] Replace operator API group janus-idp.io with rhdh.redhat.com
janus-idp/operator pull request #201
Opened 2024-02-14 01:26 UTC by jianrongzhang89

## Description

## Which issue(s) does this PR fix or relate to

- Fixes #_issue_number_

## PR acceptance criteria

- [ ] Tests
- [ ] Documentation

## How to test changes / Special notes to the reviewer

2024-02-15 10:51 UTC, kadel commented
We should also consider changing the ApiVersion to `v1`

2024-02-15 14:03 UTC, jianrongzhang89 commented
> We should also consider changing the ApiVersion to `v1`

As discussed, we will keep the ApiVersion as v1alpha1 until the API is stable.

2024-02-15 16:29 UTC, kadel commented
@jianrongzhang89 we can go ahead with rhdh.redhat.com

2024-02-15 16:42 UTC, jianrongzhang89 commented
> @jianrongzhang89 we can go ahead with rhdh.redhat.com

Sounds good. Thank you @kadel.

2024-02-17 00:16 UTC, rm3l requested changes

2024-02-17 00:16 UTC, rm3l commented on examples/rhdh-cr.yaml
> +  # generated with the command below (from https://rhdh.redhat.com/docs/auth/service-to-service-auth/#setup):
Correct link is in the upstream Backstage docs: 

```suggestion
  # generated with the command below (from https://backstage.io/docs/auth/service-to-service-auth/#setup):
```

2024-02-17 00:16 UTC, rm3l commented on examples/rhdh-cr-with-app-configs.yaml
> +  # generated with the command below (from https://rhdh.redhat.com/docs/auth/service-to-service-auth/#setup):
```suggestion
  # generated with the command below (from https://backstage.io/docs/auth/service-to-service-auth/#setup):
```

2024-02-17 00:16 UTC, rm3l commented on .rhdh/scripts/rhdh-disconnected-install/rhdh/render.json
The whole `rhdh-disconnected-install` folder should not be committed. I think it is created by the `prepare-restricted-environment.sh` script.

2024-02-17 00:16 UTC, rm3l commented on .rhdh/scripts/rhdh-disconnected-install.Dockerfile
This file should not be committed. I think it is created by the `prepare-restricted-environment.sh` script.

2024-02-17 00:16 UTC, rm3l commented on .rhdh/scripts/prepare-restricted-environment.sh
Why is this file committed? Seems like a partial cherry-pick of 72962ea, but without the docs.

2024-02-17 01:44 UTC, jianrongzhang89 commented on .rhdh/scripts/rhdh-disconnected-install.Dockerfile
Removed

2024-02-17 01:45 UTC, jianrongzhang89 commented on .rhdh/scripts/prepare-restricted-environment.sh
Removed

2024-02-17 01:45 UTC, jianrongzhang89 commented on .rhdh/scripts/rhdh-disconnected-install/rhdh/render.json
Removed

2024-02-17 01:45 UTC, jianrongzhang89 commented on bundle/manifests/backstage-default-config_v1_configmap.yaml
> +            rhdh.redhat.com/app:  # placeholder for 'backstage-<cr-name>'
Ok

2024-02-17 09:15 UTC, rm3l approved these changes

2024-02-17 09:18 UTC, merged

2024-02-19 18:39 UTC, nickboldt commented on bundle/manifests/backstage-default-config_v1_configmap.yaml
> +            rhdh.redhat.com/app:  # placeholder for 'backstage-<cr-name>'
hmm. https://janus-idp.io/ actually exists as a website.

rhdh.redhat.com however does not, but https://redhat-developer.github.io/ does - we have the product docs at https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/ for example. 

Are these URLs supposed to exist?

2024-02-19 19:10 UTC, nickboldt commented
This seems like a big change to do after feature freeze... why does it need to be done in 1.1.x AND in main? why not just in main?

2024-02-19 20:08 UTC, jianrongzhang89 commented
> This seems like a big change to do after feature freeze... why does it need to be done in 1.1.x AND in main? why not just in main?



> This seems like a big change to do after feature freeze... why does it need to be done in 1.1.x AND in main? why not just in main?
Because we'd like the first release to be based on the correct API group. Releasing it with the old group can cause more issues for customers when a newer version of operator is released later.

2024-02-19 21:28 UTC, nickboldt commented
fair point but at some point we will have to start respecting the freeze dates :D 

While the operator remains Tech Preview, this is less important, however.